logging:
  level:
    root: DEBUG

server:
  port: 8080

app:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/url-shortener-db-1
      username: root
      password: Swapy@27
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/url-shortener-db-2
      username: root
      password: Swapy@27
    db3:
      jdbc-url: jdbc:mysql://localhost:3306/url-shortener-db-3
      username: root
      password: Swapy@27


