logging:
  level:
    root: DEBUG

server:
  port: 8081


  ssl:
    key-store-type: PKCS12
    key-store: file:C:\Users\SWAPNILJ\Documents\Coding_Challenges\MTLS\server2\src\main\resources\keystore.p12
    key-store-password: changeit
    protocol: TLS
    enabled-protocol: TLSv1.2

#    trust-store-type: PKCS12
#    trust-store: file:C:\Users\SWAPNILJ\Documents\Coding_Challenges\MTLS\server2\src\main\resources\keystore.p12
#    trust-store-password: changeit
